"""change type for topic weights to float

Revision ID: 076f8490eed9
Revises: cf4593a13009
Create Date: 2021-02-04 18:17:25.034858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076f8490eed9'
down_revision = 'cf4593a13009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_distribution', 'topic_weight', schema='so_ana_analysis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_distribution', sa.Column('topic_weight', sa.INTEGER(), autoincrement=False, nullable=True), schema='so_ana_analysis')
    # ### end Alembic commands ###
