"""include ml-flag field and language detection

Revision ID: 30108f70cb3b
Revises: 72901249ace9
Create Date: 2021-01-21 16:23:27.650967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30108f70cb3b'
down_revision = '72901249ace9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_meta_info', sa.Column('ml_tag', sa.Integer(), nullable=True), schema='so_ana_doc_worker')
    op.add_column('post_results', sa.Column('ml_tag', sa.Integer(), nullable=True), schema='so_ana_management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_results', 'ml_tag', schema='so_ana_management')
    op.drop_column('page_meta_info', 'ml_tag', schema='so_ana_doc_worker')
    # ### end Alembic commands ###
