"""change type for topic weights to float part 2

Revision ID: 361fde4943a9
Revises: 076f8490eed9
Create Date: 2021-02-04 18:23:57.121585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361fde4943a9'
down_revision = '076f8490eed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_distribution', sa.Column('topic_weight', sa.Float(), nullable=True), schema='so_ana_analysis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_distribution', 'topic_weight', schema='so_ana_analysis')
    # ### end Alembic commands ###
