"""add used step columns to job overview table

Revision ID: 4760697ddc4b
Revises: 5879f2e1ada9
Create Date: 2021-01-23 20:00:43.758282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4760697ddc4b'
down_revision = '5879f2e1ada9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_overview', sa.Column('use_step_label', sa.String(length=255), nullable=True), schema='so_ana_management')
    op.add_column('job_overview', sa.Column('use_step_step', sa.String(length=255), nullable=True), schema='so_ana_management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_overview', 'use_step_step', schema='so_ana_management')
    op.drop_column('job_overview', 'use_step_label', schema='so_ana_management')
    # ### end Alembic commands ###
