"""add step info to job exc table

Revision ID: 5879f2e1ada9
Revises: f95138ae6d60
Create Date: 2021-01-22 11:56:08.668442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5879f2e1ada9'
down_revision = 'f95138ae6d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_overview', sa.Column('step_2_info', postgresql.JSON(astext_type=sa.Text()), nullable=True), schema='so_ana_management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_overview', 'step_2_info', schema='so_ana_management')
    # ### end Alembic commands ###
