"""creating initial tables

Revision ID: 72901249ace9
Revises: 7f1be83ab61c
Create Date: 2021-01-18 16:01:42.638313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72901249ace9'
down_revision = '7f1be83ab61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_meta_info',
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.Column('step_label', sa.String(length=255), nullable=False),
    sa.Column('ord_key', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('post_meta_extracted_date', sa.Date(), nullable=True),
    sa.Column('post_url', sa.String(length=1023), nullable=True),
    sa.Column('heading', sa.String(length=1023), nullable=True),
    sa.Column('excerpt', sa.String(length=2047), nullable=True),
    sa.Column('asked_date', sa.Date(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Integer(), nullable=True),
    sa.Column('answer_status', sa.String(length=255), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=255), dimensions=1), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('user_url', sa.String(length=1023), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('step', 'step_label', 'ord_key'),
    schema='so_ana_doc_worker'
    )
    op.create_table('prefect_logs',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('flow_run_id', sa.String(length=255), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('task_slug', sa.String(length=255), nullable=True),
    sa.Column('task_run_id', sa.String(length=255), nullable=True),
    sa.Column('map_index', sa.Integer(), nullable=True),
    sa.Column('task_loop_count', sa.Integer(), nullable=True),
    sa.Column('task_run_count', sa.Integer(), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('threadName', sa.String(length=255), nullable=True),
    sa.Column('process', sa.Integer(), nullable=True),
    sa.Column('processName', sa.String(length=255), nullable=True),
    sa.Column('exc_text', sa.String(length=4095), nullable=True),
    sa.Column('levelname', sa.String(length=15), nullable=True),
    sa.Column('msg', sa.String(length=4095), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('msg_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('msg_uuid'),
    schema='so_ana_logging'
    )
    op.create_table('job_overview',
    sa.Column('description', sa.String(length=2047), nullable=True),
    sa.Column('flow_name', sa.String(length=2047), nullable=True),
    sa.Column('flow_id', sa.String(length=2047), nullable=True),
    sa.Column('flow_run_id', sa.String(length=2047), nullable=False),
    sa.Column('flow_run_name', sa.String(length=2047), nullable=True),
    sa.Column('stack_exchange_type', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('download_opts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pre_proc_opts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('vect_opts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_opts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('rep_opts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at_timest', sa.DateTime(), nullable=True),
    sa.Column('finished_at_timst', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('exit_msg', sa.String(), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('flow_run_id'),
    schema='so_ana_management'
    )
    op.create_table('page_results',
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.Column('step_label', sa.String(length=255), nullable=False),
    sa.Column('ord_key', sa.Integer(), nullable=False),
    sa.Column('flow_run_id', sa.String(length=255), nullable=True),
    sa.Column('flow_run_name', sa.String(length=255), nullable=True),
    sa.Column('result_class_name', sa.String(length=255), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('exit_msg', sa.String(length=4095), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.Column('page_nr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('step', 'step_label', 'ord_key', 'result_class_name'),
    schema='so_ana_management'
    )
    op.create_table('post_results',
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.Column('step_label', sa.String(length=255), nullable=False),
    sa.Column('ord_key', sa.Integer(), nullable=False),
    sa.Column('flow_run_id', sa.String(length=255), nullable=True),
    sa.Column('flow_run_name', sa.String(length=255), nullable=True),
    sa.Column('result_class_name', sa.String(length=255), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('exit_msg', sa.String(length=4095), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('step', 'step_label', 'ord_key', 'result_class_name'),
    schema='so_ana_management'
    )
    op.create_table('steps_overview',
    sa.Column('flow_name', sa.String(length=255), nullable=True),
    sa.Column('flow_id', sa.String(length=255), nullable=True),
    sa.Column('flow_run_id', sa.String(length=255), nullable=True),
    sa.Column('flow_run_name', sa.String(length=255), nullable=True),
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.Column('step_label', sa.String(length=255), nullable=False),
    sa.Column('placed_at_timest', sa.DateTime(), nullable=True),
    sa.Column('started_at_timest', sa.DateTime(), nullable=True),
    sa.Column('finished_at_timest', sa.DateTime(), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('exit_msg', sa.String(), nullable=True),
    sa.Column('prev_step_lbls', postgresql.ARRAY(sa.String(length=255), dimensions=1), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('step', 'step_label'),
    schema='so_ana_management'
    )
    op.create_table('task_results',
    sa.Column('flow_run_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('task_slug', sa.String(length=255), nullable=False),
    sa.Column('map_index', sa.Integer(), nullable=False),
    sa.Column('task_loop_count', sa.Integer(), nullable=False),
    sa.Column('task_run_count', sa.Integer(), nullable=False),
    sa.Column('result_as_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('flow_name', sa.String(length=255), nullable=True),
    sa.Column('flow_run_name', sa.String(length=255), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('task_full_name', sa.String(length=255), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('task_run_id', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('flow_run_id', 'task_slug', 'map_index', 'task_loop_count', 'task_run_count'),
    schema='so_ana_management'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_results', schema='so_ana_management')
    op.drop_table('steps_overview', schema='so_ana_management')
    op.drop_table('post_results', schema='so_ana_management')
    op.drop_table('page_results', schema='so_ana_management')
    op.drop_table('job_overview', schema='so_ana_management')
    op.drop_table('prefect_logs', schema='so_ana_logging')
    op.drop_table('page_meta_info', schema='so_ana_doc_worker')
    # ### end Alembic commands ###
