"""added user_agent and from_email to job meta information table

Revision ID: bbce40ec01d7
Revises: cecfd30de918
Create Date: 2022-02-03 15:08:40.339976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbce40ec01d7'
down_revision = 'cecfd30de918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_overview', sa.Column('from_email', sa.String(length=255), nullable=True), schema='so_ana_management')
    op.add_column('job_overview', sa.Column('user_agent', sa.String(length=255), nullable=True), schema='so_ana_management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_overview', 'user_agent', schema='so_ana_management')
    op.drop_column('job_overview', 'from_email', schema='so_ana_management')
    # ### end Alembic commands ###
