"""generate topic table

Revision ID: cf4593a13009
Revises: 4760697ddc4b
Create Date: 2021-02-04 06:55:40.902002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4593a13009'
down_revision = '4760697ddc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_distribution',
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.Column('step_label', sa.String(length=255), nullable=False),
    sa.Column('ord_key', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('for_step', sa.String(length=255), nullable=True),
    sa.Column('for_step_label', sa.String(length=255), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_weight', sa.Integer(), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.Column('flow_run_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('task_slug', sa.String(length=255), nullable=True),
    sa.Column('task_run_id', sa.String(length=255), nullable=True),
    sa.Column('map_index', sa.Integer(), nullable=True),
    sa.Column('task_loop_count', sa.Integer(), nullable=True),
    sa.Column('task_run_count', sa.Integer(), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('process', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('step', 'step_label', 'ord_key', 'topic_id'),
    schema='so_ana_analysis'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_distribution', schema='so_ana_analysis')
    # ### end Alembic commands ###
