"""create artefact table

Revision ID: f95138ae6d60
Revises: e4e4b5b32242
Create Date: 2021-01-21 22:22:29.422265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f95138ae6d60'
down_revision = 'e4e4b5b32242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefacts',
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.Column('step_label', sa.String(length=255), nullable=False),
    sa.Column('artefact_key', sa.String(length=255), nullable=False),
    sa.Column('artefact_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('modus', sa.String(length=7), nullable=True),
    sa.Column('flow_run_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('task_slug', sa.String(length=255), nullable=True),
    sa.Column('task_run_id', sa.String(length=255), nullable=True),
    sa.Column('map_index', sa.Integer(), nullable=True),
    sa.Column('task_loop_count', sa.Integer(), nullable=True),
    sa.Column('task_run_count', sa.Integer(), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('process', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('step', 'step_label', 'artefact_key'),
    schema='so_ana_management'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artefacts', schema='so_ana_management')
    # ### end Alembic commands ###
